#!/bin/sh
set -e

# Use trusted sandbox TLS certs generated by scripts/setup-trusted-certs.sh.
if [ ! -f /etc/dovecot/certs/server.pem ] || [ ! -f /etc/dovecot/certs/server.key ]; then
    echo "Sandbox TLS certificates are missing." >&2
    echo "Run './scripts/setup-trusted-certs.sh' or 'make start' before starting Dovecot." >&2
    exit 1
fi

echo "Using sandbox TLS certificates provided in /etc/dovecot/certs..."
cp /etc/dovecot/certs/server.pem /tmp/server.pem
cp /etc/dovecot/certs/server.key /tmp/server.key
chmod 600 /tmp/server.key

# Ensure vmail user and mail directory exist
if ! id vmail >/dev/null 2>&1; then
    addgroup -g 1000 vmail 2>/dev/null || true
    adduser -D -u 1000 -G vmail -h /var/mail vmail 2>/dev/null || true
fi
mkdir -p /var/mail/testuser/Maildir/{cur,new,tmp}
chown -R vmail:vmail /var/mail

exec dovecot -F
