#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."

ENV_FILE="${ENV_FILE:-.env}"

read_env() {
    local key="$1"
    local default="$2"
    local value

    value="$(grep -E "^${key}=" "$ENV_FILE" 2>/dev/null | tail -n 1 | cut -d= -f2- || true)"
    if [ -n "$value" ]; then
        printf '%s\n' "$value"
    else
        printf '%s\n' "$default"
    fi
}

CORE_DIR="$(read_env MAILSUBSYSTEM_CORE_DIR ../MailSubsystem)"
DB_PORT="$(read_env MAILSUBSYSTEM_DB_PORT 15432)"
IMAPS_PORT="$(read_env SANDBOX_IMAPS_PORT 1993)"
IMAP_USER="$(read_env SANDBOX_IMAP_USER testuser)"
IMAP_PASS="$(read_env SANDBOX_IMAP_PASS testpass123)"

if [ ! -d "$CORE_DIR" ]; then
    echo "MailSubsystem core checkout not found: $CORE_DIR" >&2
    echo "Edit $ENV_FILE and set MAILSUBSYSTEM_CORE_DIR." >&2
    exit 1
fi

if [ ! -f dovecot/certs/ca.pem ]; then
    echo "Sandbox CA is missing. Run: make certs" >&2
    exit 1
fi

CORE_ENV="$CORE_DIR/.env"
if [ -f "$CORE_ENV" ]; then
    echo "$CORE_ENV already exists; leaving it unchanged." >&2
    echo "Move it aside first if you want this script to create a sandbox config." >&2
    exit 1
fi

CA_CERT="$(realpath dovecot/certs/ca.pem)"

cat >"$CORE_ENV" <<EOF
# Generated by mailsubsystem-dev-env.
# Add one AI provider key before running analysis.

IMAP_SERVER=localhost:${IMAPS_PORT}
IMAP_USERNAME=${IMAP_USER}
IMAP_PASSWORD=${IMAP_PASS}
IMAP_TLS_CA_CERT_FILE=${CA_CERT}

DATABASE_URL=postgresql://mailsubsystem:mailsubsystem@localhost:${DB_PORT}/mailsubsystem?sslmode=disable

# Frontier provider API keys. Set one, or configure a local OpenAI-compatible model.
# GEMINI_API_KEY=your-key-here
# OPENAI_API_KEY=sk-your-key-here
# ANTHROPIC_API_KEY=sk-ant-your-key-here

# LOCAL_LLM_URL=http://localhost:1234/v1
# LOCAL_LLM_MODEL=your-local-model-name
EOF

echo "Created $CORE_ENV for the local sandbox."
